development:
  adapter: postgresql
  encoding: unicode
  database: nested_development
  pool: 5
  username: carlgoulding
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nested_test
  pool: 5
  username: carlgoulding
  password:
